name: deploy to ec2 with jar

# 이벤트라고 부른다, main에 push 되면 아래 코드가 동작하겠다
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v2

#   ubuntu pc에 java를 깔겠다, temurin은 배포판 중 하나다, 잘 사용되는 건 아니나 깃헙액션에선 자주 사용됨
      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

#   가상 pc에서 실행할 수 있도록 권한 chmod777
      - name: build jar
        working-directory: .
        run: |
          chmod 777 ./gradlew
          ./gradlew bootJar

      - name: copy jar to ec2 inst1
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.EC2_HOST1}}
          username: ubuntu

#   pemkey를 통해 해당 인스턴스에 접근
#   source : 출발지, target : 도착지
          key: ${{secrets.EC2_PEMKEY}}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu"

      - name: install java and run jar on ec2 inst1
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST1}}
          username: ubuntu
#   pemkey를 통해 해당 인스턴스에 접근
#   sudo killall java -> 기존에 실행되고 있던 java를 킬하고 다시.. 인텔리제이 껐다가 키는 거라고 생각하면됨
          key: ${{secrets.EC2_PEMKEY}}
          script: |
            if ! type java > /dev/null; then
              sudo apt-get update && sudo apt-get install openjdk-17-jdk -y
            else
              echo "java is already installed"
            fi
            sudo killall java
            nohup java -jar /home/ubuntu/build/libs/*.jar \
            --spring.redis.host=${{secrets.REDIS_HOST}} \
            --jwt.secretKeyAt=${{secrets.AT_SECRET_KEY}} \
            --jwt.secretKeyRt=${{secrets.RT_SECRET_KEY}} \
            --spring.datasource.url=jdbc:mariadb://${{secrets.DB_HOST}}:3306/ordersystem \
            --spring.datasource.username=admin \
            --spring.datasource.password=${{secrets.DB_PW}} > /home/ubuntu/app.log 2>&1 &

# 멀티서버 환경 고려하여 만든 두번째 ec2(inst2)
      - name: copy jar to ec2 inst2
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.EC2_HOST2}}
          username: ubuntu
          #          pemkey를 통해 해당 인스턴스에 접근
          key: ${{secrets.EC2_PEMKEY}}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu"

      - name: install java and run jar on ec2 inst2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST2}}
          username: ubuntu
          #          pemkey를 통해 해당 인스턴스에 접근
          key: ${{secrets.EC2_PEMKEY}}
          script: |
            if ! type java > /dev/null; then
              sudo apt-get update && sudo apt-get install openjdk-17-jdk -y
            else
              echo "java is already installed"
            fi
            sudo killall java
            nohup java -jar /home/ubuntu/build/libs/*.jar \
            --spring.redis.host=${{secrets.REDIS_HOST}} \
            --jwt.secretKeyAt=${{secrets.AT_SECRET_KEY}} \
            --jwt.secretKeyRt=${{secrets.RT_SECRET_KEY}} \
            --spring.datasource.url=jdbc:mariadb://${{secrets.DB_HOST}}:3306/ordersystem \
            --spring.datasource.username=admin \
            --spring.datasource.password=${{secrets.DB_PW}} > /home/ubuntu/app.log 2>&1 &

